paths-ignore:
  - "path/to/file/with/figma/key.js"
  - "*.config.js"  # Ignores all config.js files

# For specific patterns
allow:
  - pattern: "figma_[a-zA-Z0-9]{32}"  # Pattern that matches your Figma key format
    description: "Allowlisted Figma API key"
    
  # You can add multiple patterns
  - pattern: "another_pattern_to_allow"
    description: "Description of this pattern"